//! DB-less world loading (Phase 1 T1.2 testability requirement).
//!
//! The fixture JSON (`tests/fixtures/world_fixture.json`) is generated by
//! `scripts/gen_world_fixture.mjs` from `scripts/seed_world.sh` — the same
//! text `scripts/check_seed_counts.sh` asserts against — and a test in
//! `tests/fixture_drift.rs` re-asserts the counts, so fixture, seed script
//! and map can never silently drift. This is also the api-server
//! `WORLD_SOURCE=fixture` path (local demo mode without a database).

use serde::Deserialize;

use crate::world::WorldState;
use crate::{Agent, LayoutItem, WorkItem, World};

#[derive(Debug, Clone, Deserialize)]
pub struct WorldFixture {
    pub world: World,
    pub agents: Vec<Agent>,
    pub layout: Vec<LayoutItem>,
    #[serde(default)]
    pub work_items: Vec<WorkItem>,
}

pub fn parse_fixture(json: &str) -> Result<WorldFixture, String> {
    serde_json::from_str(json).map_err(|e| format!("fixture: invalid JSON: {e}"))
}

impl WorldState {
    /// Builds a resident world from fixture JSON + tmj map text — no DB,
    /// no I/O beyond the strings the caller already read.
    pub fn from_fixture_strs(fixture_json: &str, tmj_str: &str) -> Result<Self, String> {
        let fx = parse_fixture(fixture_json)?;
        WorldState::from_parts(fx.world, fx.agents, fx.layout, fx.work_items, tmj_str)
    }
}

/// Convenience loader resolving the canonical in-repo files relative to
/// this crate's manifest dir (`tests/fixtures/world_fixture.json` and
/// `../../../assets/maps/office_shell.tmj`). Meant for tests and local
/// tools; api-server resolves its own paths from env instead.
pub fn load_world_state_from_fixture_files() -> Result<WorldState, String> {
    let manifest = env!("CARGO_MANIFEST_DIR");
    let fixture_path = format!("{manifest}/tests/fixtures/world_fixture.json");
    let tmj_path = format!("{manifest}/../../../assets/maps/office_shell.tmj");
    let fixture_json = std::fs::read_to_string(&fixture_path)
        .map_err(|e| format!("fixture: cannot read {fixture_path}: {e}"))?;
    let tmj_str = std::fs::read_to_string(&tmj_path)
        .map_err(|e| format!("fixture: cannot read {tmj_path}: {e}"))?;
    WorldState::from_fixture_strs(&fixture_json, &tmj_str)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fixture_files_load_into_world_state() {
        let ws = load_world_state_from_fixture_files().expect("fixture world loads");
        assert_eq!(ws.agents.len(), 9);
        assert_eq!(ws.layout.len(), 94);
        assert_eq!(ws.work_items.len(), 6);
        assert_eq!(ws.world.sim_clock_sec, 25200, "07:00 kickoff");
        assert_eq!(ws.world.tick_ms, 1000);
        assert_eq!(ws.world.sec_per_tick, 10);
        assert_eq!(ws.map.width, 48);
        assert_eq!(ws.map.height, 32);
        assert_eq!(
            ws.map.door_tiles,
            vec![(23, 31), (24, 31)],
            "main door: bottom edge center, 2 tiles wide"
        );
    }

    #[test]
    fn every_agent_resolves_a_walkable_unblocked_chair() {
        let ws = load_world_state_from_fixture_files().unwrap();
        let mut chairs = std::collections::HashSet::new();
        for a in &ws.agents {
            assert!(
                !ws.grid.is_blocked(a.chair.0, a.chair.1),
                "chair of {} must be walkable on the collision grid",
                a.agent.name
            );
            assert!(
                chairs.insert(a.chair),
                "two agents must not share chair {:?}",
                a.chair
            );
        }
    }

    #[test]
    fn parse_rejects_garbage() {
        assert!(parse_fixture("not json").is_err());
        assert!(parse_fixture("{\"world\": 3}").is_err());
    }
}
